### ISSUE TITLE
ERROR in train on MOT17

### ISSUE THREAD

**Issue by Mercuryyu** [yfzhang1214/TCBTrack#1]
Traceback (most recent call last):

  File "tools/train2.py", line 120, in <module>
    launch(
    └ <function launch at 0x7df26259b550>

> File "/home/rislab/TCBTrack/TCB/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤═══════════════════════════════════════════════════════════════╕
    │            │ keys             │ values            ...
    └ <function main at 0x7df2491ca820>

  File "tools/train2.py", line 102, in main
    trainer.train()
    │       └ <function Trainer2.train at 0x7df24924a9d0>
    └ <yolox.core.trainer2.Trainer2 object at 0x7df2491d7220>

  File "/home/rislab/TCBTrack/TCB/yolox/core/trainer2.py", line 73, in train
    self.before_train()
    │    └ <function Trainer2.before_train at 0x7df24924ac10>
    └ <yolox.core.trainer2.Trainer2 object at 0x7df2491d7220>

  File "/home/rislab/TCBTrack/TCB/yolox/core/trainer2.py", line 135, in before_train
    self.train_loader, settings = self.exp.get_data_loader2(
    │                             │    │   └ <function Exp.get_data_loader2 at 0x7df2491d15e0>
    │                             │    └ ╒══════════════════╤═══════════════════════════════════════════════════════════════╕
    │                             │      │ keys             │ values             ...
    │                             └ <yolox.core.trainer2.Trainer2 object at 0x7df2491d7220>
    └ <yolox.core.trainer2.Trainer2 object at 0x7df2491d7220>

  File "/home/rislab/TCBTrack/TCB/exps/example/mot/mot17.py", line 147, in get_data_loader2
    sampler = TwoFrameSampler(self.dataset,batch = batch_size,seed=self.seed if self.seed else 0)
              │               │    │               │               │    │       │    └ None
              │               │    │               │               │    │       └ ╒══════════════════╤═══════════════════════════════════════════════════════════════╕
              │               │    │               │               │    │         │ keys             │ values             ...
              │               │    │               │               │    └ None
              │               │    │               │               └ ╒══════════════════╤═══════════════════════════════════════════════════════════════╕
              │               │    │               │                 │ keys             │ values             ...
              │               │    │               └ 16
              │               │    └ <yolox.data.datasets.mot.MOTDataset object at 0x7df2491f0910>
              │               └ ╒══════════════════╤═══════════════════════════════════════════════════════════════╕
              │                 │ keys             │ values             ...
              └ <class 'yolox.data.samplers.TwoFrameSampler'>

  File "/home/rislab/TCBTrack/TCB/yolox/data/samplers.py", line 102, in __init__
    self.video_label = self.getlabel()
    │                  │    └ <function TwoFrameSampler.getlabel at 0x7df24b397700>
    │                  └ <yolox.data.samplers.TwoFrameSampler object at 0x7df33c9be610>
    └ <yolox.data.samplers.TwoFrameSampler object at 0x7df33c9be610>

  File "/home/rislab/TCBTrack/TCB/yolox/data/samplers.py", line 272, in getlabel
    seqs = os.listdir(path)
           │  │       └ '/data3/yfzhang/datasets/bdd100k/images/track/train'
           │  └ <built-in function listdir>
           └ <module 'os' from '/home/rislab/miniconda3/envs/tcbtrack/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/data3/yfzhang/datasets/bdd100k/images/track/train'

**Comment by yfzhang1214** [comment]
I deeply apologize for this issue. The solution to this problem is to modify the getlabel function and TwoFrameSampler class in TCBTrack/TCB/yolox/data/samplers.py. In the getlabel function, it is necessary to modify the path to the path of the desired dataset to classify videos for the training set of TwoFrameSampler. This is to ensure that the selected training pairs belong to the same video. The code will be improved and updated later. Thank you!

**Comment by Mercuryyu** [comment]
Thank you very much for opening up the code and taking time out of your busy schedule to answer my questions. I will modify the code based on your response and look forward to your updates. Thank you very much！
